# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 23:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceller',
            field=models.ForeignKey(null=True, on_delete=models.SET(store.models.get_sentinel_user), related_name='cancellers', to=settings.AUTH_USER_MODEL, verbose_name='the canceller of this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='reason_cancelled',
            field=models.CharField(max_length=100, null=True, verbose_name='if order cancelled, why?'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 929429), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 936428), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 937429), editable=False, verbose_name='date order was placed'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 938427), editable=False, verbose_name='date product was ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 934425), editable=False, verbose_name='date product was added to db'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 932928), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 939429), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 930931), editable=False, verbose_name='date shipping address was added to db'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 0, 48, 9, 935928), editable=False, verbose_name='date wish was added to db'),
        ),
    ]
