# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 1492), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 5481), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 6479), editable=False, verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 6479), editable=False, verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 4481), editable=False, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_deliveries',
            field=models.PositiveIntegerField(default=0, verbose_name='deliveries'),
        ),
        migrations.AlterField(
            model_name='product',
            name='orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='price (₦)'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 3497), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 7475), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 2497), editable=False, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 44, 53, 4481), editable=False, verbose_name='date wish was added to db'),
        ),
    ]
