# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 14:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text="type anything in this field. it'll be generated automatically", max_length=100, null=True, verbose_name='reference of the order')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=100, verbose_name='status of the order e.g pending, processing, cancelled, delivered')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 814343), editable=False, verbose_name='date order was placed')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date order details were updated last')),
                ('user', models.ForeignKey(on_delete=models.SET(store.models.get_sentinel_user), related_name='orderer', to=settings.AUTH_USER_MODEL, verbose_name='User from the user table')),
            ],
            options={
                'get_latest_by': 'created_at',
                'ordering': ['-created_at', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity of the product ordered')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='cost of one of the products ordered')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 816341), editable=False, verbose_name='date product was ordered')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date order details were updated last')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.Order', verbose_name='order product belongs to')),
            ],
            options={
                'get_latest_by': 'created_at',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image_url', models.ImageField(blank=True, max_length=255, upload_to='img/products/')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 819341), editable=False, verbose_name='date image was added to db')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date image was updated last')),
            ],
            options={
                'get_latest_by': 'created_at',
                'ordering': ['product_id'],
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_per_unit',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_image_url',
            field=models.ImageField(blank=True, max_length=255, upload_to='img/brands/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='desc',
            field=models.CharField(default='We sell great stuff', max_length=255, verbose_name='description of brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='We sell great stuff', max_length=255, verbose_name='description of product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, verbose_name='number of sales of this product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='cat_image_url',
            field=models.ImageField(blank=True, max_length=255, upload_to='img/cat/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='desc',
            field=models.CharField(default='for men only', max_length=255, verbose_name='description of product category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 797302), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 811302), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(verbose_name='quantity of the product added'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date cart product details were updated last'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 806302), editable=False, verbose_name='date product was added to db'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.CharField(help_text="type anything in this field. it'll be generated automatically", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 802303), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 800302), editable=False, verbose_name='date shipping address was added to db'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 20, 48, 809303), editable=False, verbose_name='date wish was added to db'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='store.Product', verbose_name='product image belongs to'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='store.Product', verbose_name='product ordered'),
        ),
    ]
