# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('content', models.TextField(editable=False, max_length=255, verbose_name='feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='feedback was made')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.Order', verbose_name='order'),
        ),
    ]
