# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180131_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 798028), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Please use the following format: <em>+234 XXX XXX XXXX</em>.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 801026), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 802027), editable=False, verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 803027), editable=False, verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 800028), editable=False, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 799028), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name of category'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 803027), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 799028), editable=False, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Please use the following format: <em>+234 XXX XXX XXXX</em>.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 13, 53, 58, 801026), editable=False, verbose_name='date wish was added to db'),
        ),
    ]
