# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180119_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 661232), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 662236), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 662236), editable=False, verbose_name='date order was placed'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 662236), editable=False, verbose_name='date product was ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 662236), editable=False, verbose_name='date product was added to db'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 662236), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 662236), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 662236), editable=False, verbose_name='date shipping address was added to db'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 1, 28, 10, 662236), editable=False, verbose_name='date wish was added to db'),
        ),
    ]
