# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180212_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='True', help_text='Please use the following format: <em>+234 XXX XXX XXXX</em>.', max_length=128),
        ),
    ]
