# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 01:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180101_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'get_latest_by': 'created_at', 'ordering': ['order'], 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'get_latest_by': 'created_at', 'ordering': ['product_id'], 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'get_latest_by': 'created_at', 'ordering': ['user_id'], 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_url',
            field=models.CharField(help_text="type anything in this field. it'll be generated automatically", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 772600), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 790163), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='store.Product', verbose_name='product in the cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(store.models.get_sentinel_user), related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User from the user table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 793145), editable=False, verbose_name='date order was placed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(store.models.get_sentinel_user), related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User from the user table'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 795144), editable=False, verbose_name='date product was ordered'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.Order', verbose_name='order product belongs to'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.Product', verbose_name='product ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='admin',
            field=models.ForeignKey(on_delete=models.SET(store.models.get_sentinel_user), related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Admin from the user table'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.Brand', verbose_name='Brand of the Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.ProductCategory', verbose_name='Category of the Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 785143), editable=False, verbose_name='date product was added to db'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, verbose_name='number of sales of this product'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='cat_image_url',
            field=models.ImageField(blank=True, max_length=255, upload_to='img/product_categories/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 781110), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 798160), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.Product', verbose_name='product image belongs to'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 777098), editable=False, verbose_name='date shipping address was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(store.models.get_sentinel_user), related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='User from the user table'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 2, 33, 788155), editable=False, verbose_name='date wish was added to db'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='store.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL, verbose_name='User from the user table'),
        ),
    ]
