# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 03:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180131_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmed delivered (cusotmer)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 115611), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 119111), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 120111), editable=False, verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered (tetris)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reason_cancelled',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='if order is cancelled, why?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, help_text='this field is generated automatically', max_length=100, null=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 121138), editable=False, verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 118111), editable=False, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 117111), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 121625), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 116611), editable=False, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 3, 4, 38, 32, 118611), editable=False, verbose_name='date wish was added to db'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
