# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180105_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 201258), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 217246), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 220216), editable=False, verbose_name='date order was placed'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 223219), editable=False, verbose_name='date product was ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 212234), editable=False, verbose_name='date product was added to db'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 208227), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 225235), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 205222), editable=False, verbose_name='date shipping address was added to db'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 2, 5, 41, 215234), editable=False, verbose_name='date wish was added to db'),
        ),
    ]
