# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180121_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_date',
            field=models.DateTimeField(null=True, verbose_name='date order was delivered'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 104392), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 107391), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 107891), editable=False, verbose_name='date order was placed'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 108391), editable=False, verbose_name='date product was ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 105890), editable=False, verbose_name='date product was added to db'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 105390), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 108891), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 104891), editable=False, verbose_name='date shipping address was added to db'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 6, 43, 5, 106891), editable=False, verbose_name='date wish was added to db'),
        ),
    ]
