# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180203_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True, verbose_name='email token'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirm_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmed delivered (customer)'),
        ),
    ]
