# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 00:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180115_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 220187), editable=False, verbose_name='date brand was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 220187), editable=False, verbose_name='date cart product was added to db'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(store.models.get_sentinel_user), related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User from the user table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 220187), editable=False, verbose_name='date order was placed'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 220187), editable=False, verbose_name='date product was ordered'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 220187), editable=False, verbose_name='date product was added to db'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 220187), editable=False, verbose_name='date product category was added to db'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 235826), editable=False, verbose_name='date image was added to db'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 220187), editable=False, verbose_name='date shipping address was added to db'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 1, 11, 4, 220187), editable=False, verbose_name='date wish was added to db'),
        ),
    ]
